apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: database
    env: production
spec:
  selector:
    matchLabels:
      app: database
      env: production
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: database
        env: production
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:latest
        name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        - name: config-volume
          mountPath: /config
        - name: secret-volume
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
      - name: config-volume
        configMap:
          name: mongo-db-configmap
      - name: secret-volume
        secret:
          secretName: mongo-db-secret