apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: database
    env: production
spec:
  ports:
    - port: 27017
  selector:
    app: database
    env: production
  clusterIP: None
