apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
  labels:
    app: database
    env: production
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==